### ISSUE TITLE
Carousel crashes with scrolling in list

### ISSUE THREAD

**Issue by baksha97** [theobouwman/flutter_image_carousel#7]
`VERBOSE-2:dart_error.cc(16)] Unhandled exception:
A TabController was used after being disposed.
Once you have called dispose() on a TabController, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:61:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:67:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:134:12)
#3      TabController._changeIndex (package:flutter/src/material/tab_controller.dart:120:7)
#4      TabController.animateTo (package:flutter/src/material/tab_controller.dart:163:5)
#5      _ImageCarouselState.initState.<anonymous closure> (package:image_carousel/src/image_carousel.dart:39:24)
#6      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#7      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#8      _RawReceivePortImpl._handleMessage (dart:i<…>
`

I'm using the fluttergallery cards example and replacing that image with an image carousel and receiving this crash.

**Comment by Aman-US-Punjabi** [comment]
Carousel is crashing the app
